### ISSUE TITLE
Use a config file for test settings

### ISSUE THREAD

**Issue by asomers** [asomers/fsx-rs#12]
fsx already has a lot of command line options.  Adding additional operation types will only complicate the CLI further.  Instead, most configuration should be done by a config file.  I suggest something like this:

fsx.toml
```toml
# Options that control how a test is executed
[run]
opnum = 1
monitor = { min = 4096, max = 8192 }
numops = 10
artifacts_dir = "/tmp"
seed = 72
filename = "/mnt/foo.fsx"

# General options that control the contents of the test
[config]
flen = 262144
nosizechecks = false
blockmode = false

# Options related to the statistical distribution of operation sizes
[opsize]
max = 65536
min = 0
align = 4096

# Relative frequencies of various operations
[weights]
close_open = 1
read = 10
write = 10
mapread = 10
mapwrite = 10
invalidate = 1
```
